using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cinemachine;

[RequireComponent(typeof(CharacterController))]
public class FPSController : MonoBehaviour
{
	[SerializeField]
    private CinemachineVirtualCamera playerCamera;

    [SerializeField]
    private float walkSpeed = 6f;

    [SerializeField]
    private float runSpeed = 12f;

    [SerializeField]
    private float jumpPower = 7f;

    [SerializeField]
    private float gravity = 10f;

    [SerializeField]
    private float lookSpeed = 2f;

    [SerializeField]
    private float lookXLimit = 45f;

    private Vector3 moveDirection = Vector3.zero;
    private float rotationX = 0;

    private bool canMove = true;
    public bool CanMove { get; }

    private CharacterController characterController;

    private StateMode stateScript;

    void Start()
    {
        characterController = GetComponent<CharacterController>();
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = true;

        stateScript = FindObjectOfType<StateMode>();
    }

    void Update()
    {
        if (!stateScript.GetPuzzleMode())
        {
            // Movement
            Vector3 forward = transform.TransformDirection(Vector3.forward);
            Vector3 right = transform.TransformDirection(Vector3.right);

            // Press Left Shift to run
            bool isRunning = Input.GetKey(KeyCode.LeftShift);
            float curSpeedX = canMove
                ? (isRunning ? runSpeed : walkSpeed) * Input.GetAxis("Vertical")
                : 0;
            float curSpeedY = canMove
                ? (isRunning ? runSpeed : walkSpeed) * Input.GetAxis("Horizontal")
                : 0;
            float movementDirectionY = moveDirection.y;
            moveDirection = (forward * curSpeedX) + (right * curSpeedY);

            // Jump
            if (Input.GetButton("Jump") && !stateScript.GetPuzzleMode() && characterController.isGrounded)
            {
                moveDirection.y = jumpPower;
            }
            else
            {
                moveDirection.y = movementDirectionY;
            }

            if (!characterController.isGrounded)
            {
                moveDirection.y -= gravity * Time.deltaTime;
            }

            // Rotation
            characterController.Move(moveDirection * Time.deltaTime);

            rotationX += -Input.GetAxis("Mouse Y") * lookSpeed;
            rotationX = Mathf.Clamp(rotationX, -lookXLimit, lookXLimit);
            playerCamera.transform.localRotation = Quaternion.Euler(rotationX, 0, 0);
            transform.rotation *= Quaternion.Euler(0, Input.GetAxis("Mouse X") * lookSpeed, 0);
        }
    }
}
